name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            GOOS: darwin
          - os: ubuntu-latest
            GOOS: windows
          - os: ubuntu-latest
            GOOS: linux
          - os: ubuntu-latest
            GOOS: freebsd
          - os: ubuntu-latest
            GOOS: openbsd
          - os: ubuntu-latest
            GOOS: netbsd
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        env:
          GOOS: ${{ matrix.GOOS }}
        run: |
          go build ./example/main.go
          ls -la
